### ISSUE TITLE
Usar mediana em vez de média

### ISSUE THREAD

**Issue by stees** [cem-usp/dash-iptu#20]
Acho que é o caso de avaliar o custo computacional e considerar o uso de mediana em vez de média nos indicadores calculados, já que pelas agregações, isso indicaria o caso típico e evitaria que a média dentro de delimitações territoriais com casos extremos fosse puxada "artificialmente" pra cima ou pra baixo (exemplo clássico: distrito da Vila Andrade, com Panamby e Paraisópolis no mesmo local).

**Comment by feromes** [comment]
Existe uma limitação técnica da biblioteva Vaex que permite trabalhar com os 83 milhões de registros de uma vez só e que calcula média, mas não a mediana nem percentil, quartil, moda, etc ....  Eles prometem implementar esse recurso. Vou deixar esse Issue aqui em aberto para lembrar

**Comment by feromes** [comment]
Um aviso foi descrito em cada uma das descrições de atributos para alertar quem for trabalhar com os dados
