### ISSUE TITLE
Metadado junto ao dado

### ISSUE THREAD

**Issue by stees** [cem-usp/dash-iptu#22]
Considerando que, pensando no fluxo do usuário médio - e às vezes até mesmo pra pesquisadores -, é um tanto quanto raro abrir a aba separada para ver o que define aquele indicador, pode ser útil pensar numa maneira, dentro da interface do mapa mesmo, de colocar os metadados.

Pode até ser uma versão reduzida ou resumida e depois na aba ter a coisa mais longa, mas acho que já ter junto ao dado aumenta as chances de um maior número de pessoas ter contato com o metadado.

**Comment by feromes** [comment]
Implementado!

@stees contribuições para os textos das descrições são bemvindas!

Elas estão na pasta https://github.com/cem-usp/dash-iptu/tree/main/descricao_atributos e o formato é MarkDown
