### ISSUE TITLE
Agregação Espacial

### ISSUE THREAD

**Issue by henriquereale** [cem-usp/dash-iptu#4]
Se possível, adicionar ao dash os seguintes campos atualmente ocultos: subprefeituras, zona OD e CODLOGS. Na base do IPTU, por acaso, temos informações de latitude e longitude? Se sim, seria interessante como output para a exportação de dados (para a visualização no mapa acho que não é fundamental).

**Comment by feromes** [comment]
Feito agregação pela OD e por SUB agora falta por CODLog.

Em relação à sugestão do mapa, acho mais pragmático já fazer o download do mapa #8 criei um novo issue para isso
