### ISSUE TITLE
Classificação das Unidades Condominiais e Classificações de Uso

### ISSUE THREAD

**Issue by henriquereale** [cem-usp/dash-iptu#6]
No dash, temos unidades totais e unidades condominiais. As unidades totais agregam tanto unidades residenciais quanto comerciais? Se tivermos na base unidades residenciais e comerciais, talvez possamos separar em:

- Unidades Residenciais Horizontais
- Unidades Comerciais Horizontais
- Unidades Residenciais Verticais
- Unidades Comerciais Verticais

Se na base não tivermos a divisão entre horizontal e vertical, acho que a divisão entre residencial e comercial já seria super interessante

**Comment by feromes** [comment]
Realmente esse é um dado muito relevante, mas talvez careça de alguns critérios, sobretudo na definição do que é vertical e do que é horizontal. Poderia ser tanto um critério bibliográfico ou mesmo legal para essas definições para então classificar quanto à esse aspecto formal.

Em relação ao tipo de uso a lógica é a mesma, no entanto, precisamos qualificar cada um dos tipos de uso estabelecidos no cadastro para então classificar cada um quanto ao uso. 

Empiricamente acredito que poderíamos classificar entre:

- Residencial
- Comercial/Serviço
- Industrial 
- Outros Usos

Fico no aguardo das sugestões de critérios para essas classificações

**Comment by henriquereale** [comment]
Acho que essas 4 classificações estão ótimas. Quanto a horizontal ou vertical, acho que não precisamos necessariamente classificar a base, porque acredito que não temos algo fácil que represente isso na base. Caso o usuário queira fazer a divisão, poderia fazer uma análise com o número de pavimentos.

**Comment by feromes** [comment]
Para podermos utilizar essas classificações, é necessário fazer uma análise dos campos: TIPO DE USO DO IMOVEL e TIPO DE USO DO IMOVEL. Elas podem variar de denominação pelos anos e muitas delas podem não ser triviais para encaixar nessas classificações.

**Comment by feromes** [comment]
@henriquereale eu acabei criando uma pasta aqui chamada de `critérios` (https://github.com/cem-usp/dash-iptu/tree/main/criterios) contendo dois arquivos resultados de um processamento dos campos TIPO DE USO DO IMOVEL e TIPO DE PADRAO DA CONSTRUCAO. 

O processamento para estes aqruivos está aqui nesse Notebook https://github.com/cem-usp/dash-iptu/blob/main/03%20-%20Estudando%20Tipos%20de%20Uso%20de%20im%C3%B3vel.ipynb e basicamente tenta organizar o conteudo desses campos tornando todos os anos em um padrão único e criando criários de agrupamento do uso conforme: 

-     Residencial
-     Comercial/Serviço
-     Industrial
-     Outros Usos

O processo á automático e eu uma ajuda para validá-los seria bemvinda. Basta uma passada de olho nos registros de ambos os arquivos na pasta para saber se os atributos gerados fazem sentido ou estão inconsistentes.

Abcs,

**Comment by henriquereale** [comment]
@feromes boa noite! Acabei de verificar os registros, parece estar tudo certo! Parabéns, Fernando!! O dash vai ficar muito completo!
