### ISSUE TITLE
Base  IPTU - Tipologias

### ISSUE THREAD

**Issue by henriquereale** [cem-usp/dash-iptu#7]
Na base trabalhada para montagem do dash, temos as informações de tipologia de cada unidade? Além da metragem, seria bem legal termos a possibilidade de analisar se tivemos mais cadastros de unidades de 2 dormitórios em um ano, studios em outro e etc, se disponível na base, claro.

**Comment by feromes** [comment]
Seria realmente muito interessante, mas essa é uma limitação da base do IPTU, não existe informação sobre a tipologia, mas é possível fazer alguma inferência caso exista bibliografia ou legislação para isso. Caso haja alguma sugestão de critério para essa inferência podemos abrir novamente esse Issue.
